%% Generated by the Erlang ASN.1 compiler version:1.6.18
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module FunnelAsn



-record('BindRequest',{
connectionId, remoteIp, customerId, userId, password, type, isCached, timestamp, expiration}).

-record('PreciseTime',{
time, milliseconds}).

-record('BindResponse',{
connectionId, result}).

-record('Customer',{
id, uuid, priority, rps = asn1_NOVALUE, allowedSources, defaultSource = asn1_NOVALUE, networks, providers, defaultProviderId = asn1_NOVALUE, receiptsAllowed, noRetry, defaultValidity, maxValidity}).

-record('Provider',{
id, gateway, bulkGateway, receiptsSupported}).

-record('Network',{
id, countryCode, numbersLen, prefixes, providerId}).

-record('DisconnectRequest',{
customerId, userId, connectionId = asn1_NOVALUE}).

-record('DisconnectResponse',{
}).

-record('ConnectionsRequest',{
}).

-record('ConnectionsResponse',{
connections}).

-record('ThroughputRequest',{
}).

-record('ThroughputResponse',{
slices}).

-record('Slice',{
periodStart, counters}).

-record('Counter',{
connectionId, direction, count}).

-record('Connection',{
connectionId, remoteIp, customerId, userId, connectedAt, type, msgsReceived, msgsSent, errors}).

-record('ServerUpEvent',{
timestamp}).

-record('ServerDownEvent',{
timestamp}).

-record('ConnectionUpEvent',{
connectionId, customerId, userId, type, connectedAt, timestamp}).

-record('ConnectionDownEvent',{
connectionId, customerId, userId, type, connectedAt, msgsReceived, msgsSent, errors, reason, timestamp}).

-record('Error',{
errorCode, timestamp}).

-record('OutgoingBatch',{
id, messages}).

-record('OutgoingMessage',{
source, dest, message, dataCoding}).

-record('ReceiptBatch',{
id, receipts}).

-record('DeliveryReceipt',{
messageId, submitDate, doneDate, messageState, source, dest}).

-record('BatchAck',{
batchId}).

-record('Addr',{
addr, ton, npi}).

