#!/bin/bash

if [[ $# != 1 ]]; then
    echo "usage: dummy_server <port>"
    exit 1
fi

PORT=$1

RESPONSE="HTTP/1.1 200 OK\nContent-Type: text/plain\nContent-Length: 0\n\n"

while true; do
    echo -e ${RESPONSE} | nc -l ${PORT}
    if [[ $? != 0 ]]; then
        exit $?
    fi
    echo; date; echo
done
