#!/bin/bash

HOST=127.0.0.1
PORT=8081
CUSTOMER=oneapi-postpaid
USER=user
PASSWORD=password

curl -v --user $CUSTOMER@$USER:$PASSWORD -X DELETE $HOST:$PORT/1/smsmessaging/inbound/subscriptions/$1
echo
