#!/bin/bash

HOST=127.0.0.1
PORT=8081
CUSTOMER=oneapi-postpaid
USER=user
PASSWORD=password
DEST_ADDR=tel%3A%2B375296660003
CORRELATOR=$RANDOM
REQ_BODY="clientCorrelator=$CORRELATOR&notifyURL=http://www.yourURL.here&criteria=GIGPICS&callbackData=doSomething()"

echo request body: $REQ_BODY

curl -v --user $CUSTOMER@$USER:$PASSWORD -X POST $HOST:$PORT/1/smsmessaging/outbound/$DEST_ADDR/subscriptions -d $REQ_BODY
echo
