#!/bin/bash

HOST=127.0.0.1
PORT=8081
CUSTOMER=oneapi-postpaid
USER=user
PASSWORD=password

SENDER_ADDR=tel%3A%2B375296660003
INVALID_SENDER_ADDR=tel%3A%2B375396660003

MESSAGE_BODY=TEST

CORRELATOR=$RANDOM
#CORRELATOR=25024

REQUEST_BODY="address=tel%3A%2B375296543210&senderAddress=$SENDER_ADDR&message=$MESSAGE_BODY&clientCorrelator=$CORRELATOR";

echo "Correlator: $CORRELATOR";
echo "Request body: $REQUEST_BODY";
echo "==========================="

curl -v --user $CUSTOMER@$USER:$PASSWORD -X POST $HOST:$PORT/1/smsmessaging/outbound/$SENDER_ADDR/requests -d $REQUEST_BODY
echo
