#!/bin/bash

REQ_ID=$1
HOST=127.0.0.1
PORT=8081
CUSTOMER=oneapi-postpaid
USER=user
PASSWORD=password
SENDER_ADDR=tel%3A%2B375296660003

curl -v --user $CUSTOMER@$USER:$PASSWORD -X GET $HOST:$PORT/1/smsmessaging/outbound/$SENDER_ADDR/requests/$REQ_ID/deliveryInfos
echo
