#!/bin/bash

HOST=127.0.0.1
PORT=8081
CUSTOMER=oneapi-postpaid
USER=user
PASSWORD=password
DEST_ADDR=tel%3A%2B375296660003
NOTIFY_URL=http://localhost:1234
CORRELATOR=$RANDOM
CALLBACK='doSomething()'
REQ_BODY="destinationAddress=$DEST_ADDR&notifyURL=$NOTIFY_URL&criteria=$CRITERIA\
&notificationFormat=JSON&callbackData=$CALLBACK&clientCorrelator=$CORRELATOR"

echo "Request body: $REQUEST_BODY";
echo "==========================="

curl -v --user $CUSTOMER@$USER:$PASSWORD -X POST $HOST:$PORT/1/smsmessaging/inbound/subscriptions -d $REQ_BODY
echo
