#!/bin/bash

if [[ $# != 1 ]]; then
    echo "usage: unsubscribe_from_inbound_notifications <sub_id>"
    exit 1
fi

HOST=127.0.0.1
PORT=8081
CUSTOMER=10007
USER=user
PASSWORD=password

SUB_ID=$1

curl -v --user $CUSTOMER:$USER:$PASSWORD -X DELETE $HOST:$PORT/1/smsmessaging/inbound/subscriptions/${SUB_ID}
echo
