#!/bin/bash

REQ_ID=$1
HOST=127.0.0.1
PORT=8081
CUSTOMER=test-sys-id
USER=user
PASSWORD=password
SENDER_ADDR=tel%3A%2B375296662323

lwp-request -C $CUSTOMER@$USER:$PASSWORD -UsSe -m 'GET' $HOST:$PORT/2/smsmessaging/outbound/$SENDER_ADDR/requests/$REQ_ID/deliveryInfos; echo
