#!/bin/bash

HOST=127.0.0.1
PORT=8081
CUSTOMER=oneapi-postpaid
USER=user
PASSWORD=password
DEST_ADDR=tel%3A%2B375296660003
CORRELATOR=$RANDOM
REQ_BODY="clientCorrelator=$CORRELATOR&notifyURL=http://www.yourURL.here&criteria=GIGPICS&callbackData=doSomething()"

echo request body: $REQ_BODY

echo -n $REQ_BODY | lwp-request -C $CUSTOMER@$USER:$PASSWORD -UsSe -m 'POST' $HOST:$PORT/2/smsmessaging/outbound/$DEST_ADDR/subscriptions; echo
