#!/bin/bash

HOST=127.0.0.1
PORT=8081
CUSTOMER=oneapi-postpaid
USER=user
PASSWORD=password
DEST_ADDR=tel%3A%2B375296660003

curl -v --user $CUSTOMER@$USER:$PASSWORD -X DELETE $HOST:$PORT/2/smsmessaging/outbound/$DEST_ADDR/subscriptions/$1
echo